# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 01:43
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.hashers import make_password


def add_dispatch_user(apps, schema_editor):
    User = apps.get_model("auth", "user")
    u = User(
        username="dispatch",
        email="dispatch@crowdrescue.org",
    )
    u.password = make_password("irmaH3roes")
    u.save()


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_dispatch_user,
            reverse_code=migrations.RunPython.noop
        ),
    ]
